### ISSUE TITLE
Composer install trouble

### ISSUE THREAD

**Issue by R1maro** [YasinDehfuli/first-laravel#1]
my Composer install does not work can you help me?

**Comment by YasinDehfuli** [comment]
If you use Windows/xampp Go to the php.ini file
Remove the first semicolon of extent gd

then use : 

```bash
  composer install 
```
in your bash terminal , it will fix your problem.

**Comment by R1maro** [comment]
thanks dude <3 Fixed

**Comment by YasinDehfuli** [comment]
Your Welcome , I'm glad it was useful for you
